/**
 * Data Center — AI Agent Simulation — CRM engine.
 *
 * Generates Netvill-style IT support cases for the simulated office's
 * client base, assigns them to agents per their case_focus / clearance,
 * and tracks "compare alternatives" events (an agent finding a better/worse
 * answer outside the app) which feed back into that agent's effective
 * model_usage_rate over time.
 *
 * Volume: ~50 cases/day, 7 days/week (~350 cases/week), generated by
 * .github/workflows/agent-cases.yml and/or the scheduler's daily cycle.
 *
 * Case shape (persisted to the `cases` table — see schema.sql Part 10 for
 * the added client_name/severity/is_unique_client/requires_it_chief columns):
 *   { id, title, client_name, severity, category, description, assigned_to,
 *     difficulty, platform, is_unique_client, requires_it_chief, status }
 *
 * Status: DRAFT (Phase 1 foundation, Phase 2 CRM system).
 */

import { CASE_POOL } from './case-generator.js';

/** Netvill-style client roster. "unique" clients are wealthy/VIP accounts. */
export const CLIENT_POOL = [
  { name: 'Northgate Logistics', tier: 'standard', industry: 'logistics' },
  { name: 'Solaris Biotech', tier: 'standard', industry: 'biotech' },
  { name: 'Meridian Law Group', tier: 'standard', industry: 'legal' },
  { name: 'Pinegrove School District', tier: 'standard', industry: 'education' },
  { name: 'Cobalt Retail Co.', tier: 'standard', industry: 'retail' },
  { name: 'BrightPath Insurance', tier: 'standard', industry: 'insurance' },
  { name: 'Quarry Manufacturing', tier: 'standard', industry: 'manufacturing' },
  { name: 'Lumen Media Group', tier: 'standard', industry: 'media' },
  { name: 'Ridgeline Construction', tier: 'standard', industry: 'construction' },
  { name: 'Falcon Freight', tier: 'standard', industry: 'logistics' },
  { name: 'Nimbus Cloud Startups', tier: 'standard', industry: 'tech' },
  { name: 'Cedarwood Hotels', tier: 'standard', industry: 'hospitality' },
  { name: 'Vanta Capital Partners', tier: 'unique', industry: 'finance' },
  { name: 'Aurora Medical Center', tier: 'unique', industry: 'healthcare' },
  { name: 'Heritage Bank & Trust', tier: 'unique', industry: 'finance' },
];

/** Severity distribution weights (sum need not be 1 — relative weights). */
const SEVERITY_WEIGHTS = [
  { severity: 'low', weight: 35 },
  { severity: 'medium', weight: 40 },
  { severity: 'high', weight: 18 },
  { severity: 'critical', weight: 7 },
];

/**
 * Platform distribution weights: 1COM (30%), MirtaPBX (20%), general IT (50%).
 * Matches config/simulation-config.json case_distribution and the
 * knowledge-base expansion in data/1com.json + data/mirtapbx.json.
 */
const PLATFORM_WEIGHTS = [
  { platform: '1com',    weight: 30 },
  { platform: 'mirtapbx', weight: 20 },
  { platform: 'general', weight: 50 },
];

/** Picks a case template using weighted platform selection. */
function selectCaseTemplate() {
  const platformPick = weightedPick(PLATFORM_WEIGHTS).platform;
  const subset = platformPick === 'general'
    ? CASE_POOL.filter((t) => t.platform !== '1com' && t.platform !== 'mirtapbx')
    : CASE_POOL.filter((t) => t.platform === platformPick);
  return randomItem(subset.length ? subset : CASE_POOL);
}

const DAILY_VOLUME = 50;
const WEEK_DAYS = 7;

function pad(n, len) {
  return String(n).padStart(len, '0');
}

function randomItem(arr) {
  return arr[Math.floor(Math.random() * arr.length)];
}

function weightedPick(weighted) {
  const total = weighted.reduce((sum, w) => sum + w.weight, 0);
  let roll = Math.random() * total;
  for (const w of weighted) {
    if (roll < w.weight) return w;
    roll -= w.weight;
  }
  return weighted[weighted.length - 1];
}

function isoWeekNumber(date) {
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  return Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
}

/**
 * Generates one simulated work day's worth of CRM cases (~50 by default).
 * @param {number} dayIndex - 1-7, the simulated work day within the week
 * @param {object} [opts]
 * @param {number} [opts.count] - override DAILY_VOLUME
 * @param {number} [opts.weekNumber]
 * @param {number} [opts.year]
 */
export function generateDailyCaseBatch(dayIndex, opts = {}) {
  const now = new Date();
  const w = opts.weekNumber ?? isoWeekNumber(now);
  const y = opts.year ?? now.getFullYear();
  const count = opts.count ?? DAILY_VOLUME;

  const cases = [];
  for (let i = 1; i <= count; i++) {
    const template = selectCaseTemplate();
    const client = randomItem(CLIENT_POOL);
    const { severity } = weightedPick(SEVERITY_WEIGHTS);

    const isUniqueClient = client.tier === 'unique';
    // Hard/critical cases may require the IT Chief — includes VoIP platforms
    // because 1COM/MirtaPBX cluster and integration issues are senior work.
    const requiresItChief =
      severity === 'critical' ||
      (severity === 'high' && (
        ['network', 'firewall', 'routing'].includes(template.category) ||
        ['1com', 'mirtapbx'].includes(template.platform)
      ) && Math.random() < 0.5);

    cases.push({
      id: `crm-${y}-w${pad(w, 2)}-d${dayIndex}-${pad(i, 3)}`,
      title: template.title,
      client_name: client.name,
      severity,
      category: template.category,
      platform: template.platform,
      difficulty: template.difficulty,
      description: `[${client.name}] ${template.description}`,
      is_unique_client: isUniqueClient,
      requires_it_chief: requiresItChief,
      status: 'open',
    });
  }
  return cases;
}

/**
 * Generates a full simulated work week (7 days x ~50 cases = ~350).
 * @param {object} [opts] - forwarded to generateDailyCaseBatch per day
 * @returns {Array<Array<object>>} one array of cases per day
 */
export function generateWeeklyCaseBatches(opts = {}) {
  const batches = [];
  for (let day = 1; day <= WEEK_DAYS; day++) {
    batches.push(generateDailyCaseBatch(day, opts));
  }
  return batches;
}

/* ───────────────────────────── Assignment ─────────────────────────────── */

/**
 * Assigns a CRM case to an agent ID per agents-config.json case_focus /
 * clearance. Agents 6-9 now receive ~20% of general cases (5% each) so
 * they appear in D1 daily — they handle them as supplementary review/audit
 * work via agent-stub.js. The remaining 80% splits across workers 1-3 as
 * before.
 *
 * @param {object} caseObj - a case from generateDailyCaseBatch
 * @returns {number} agent id (1-11)
 */
export function assignCase(caseObj) {
  // Critical, IT-Chief-required cases go to the IT Chief (5), overflowing
  // to the Architect (10) for true root-level escalations.
  if (caseObj.requires_it_chief) {
    return caseObj.severity === 'critical' && Math.random() < 0.25 ? 10 : 5;
  }

  // Unique/VIP clients: per agent_11.unique_client_cases (~20% of the
  // CEO's caseload is unique-client work), route a slice of these to the
  // CEO, with the rest going to the IT Chief for hands-on work.
  if (caseObj.is_unique_client) {
    return Math.random() < 0.4 ? 11 : 5;
  }

  // Trainee (4): beginner/intermediate cases, building confidence.
  if (caseObj.difficulty === 'beginner' && Math.random() < 0.4) return 4;
  if (caseObj.difficulty === 'intermediate' && Math.random() < 0.2) return 4;

  // Hard/advanced cases occasionally escalate straight to the Architect.
  if (caseObj.difficulty === 'advanced' && Math.random() < 0.1) return 10;

  // Admin agents (6-9): 5% each = 20% total of the general pool, handled
  // as supplementary review/audit work (agent-stub.js).
  const adminRoll = Math.random();
  if (adminRoll < 0.05) return 6;
  if (adminRoll < 0.10) return 7;
  if (adminRoll < 0.15) return 8;
  if (adminRoll < 0.20) return 9;

  // Remaining 80% splits across the three general workers.
  return randomItem([1, 2, 3]);
}

/**
 * Generates a day's batch and assigns each case to an agent.
 * @returns {Array<object>} cases with `assigned_to` populated
 */
export function generateAssignedDailyBatch(dayIndex, opts = {}) {
  return generateDailyCaseBatch(dayIndex, opts).map((c) => ({ ...c, assigned_to: assignCase(c) }));
}

/* ───────────────────────────── Persistence ────────────────────────────── */

/**
 * Inserts a batch of CRM cases into the `cases` table, including the
 * client_name/severity/is_unique_client/requires_it_chief columns added
 * in schema.sql Part 10.
 */
export async function persistCrmCases(env, cases) {
  if (!env.DB || cases.length === 0) return;
  const stmt = env.DB.prepare(
    `INSERT OR IGNORE INTO cases
       (id, title, platform, difficulty, category, description, assigned_to, status, client_name, severity, is_unique_client, requires_it_chief)
     VALUES (?, ?, ?, ?, ?, ?, ?, 'open', ?, ?, ?, ?)`
  );
  await env.DB.batch(
    cases.map((c) =>
      stmt.bind(
        c.id,
        c.title,
        c.platform,
        c.difficulty,
        c.category,
        c.description,
        c.assigned_to ?? null,
        c.client_name,
        c.severity,
        c.is_unique_client ? 1 : 0,
        c.requires_it_chief ? 1 : 0
      )
    )
  );
}

/* ─────────────────────────── Compare alternatives ──────────────────────── */

/**
 * Records a "compare alternatives" event: an agent (typically Agent 2, The
 * Productive — see its FOUND-OUTSIDE PATTERN behavioral rule) compared
 * Claude's answer against an externally-found answer for the same case.
 *
 * Stored as an `interactions` row (type='compare_alternatives') so it
 * shows up in the existing session feed without new schema.
 *
 * @param {object} env
 * @param {object} opts
 * @param {number} opts.agentId
 * @param {string} [opts.sessionId] - current session id, if any
 * @param {string} opts.caseId
 * @param {boolean} opts.claudeWasBetter - true if Claude's answer won the comparison
 * @param {string} [opts.details] - short free-text note (mock report summary, etc.)
 */
export async function recordCompareAlternatives(env, { agentId, sessionId, caseId, claudeWasBetter, details }) {
  if (!env.DB) return null;
  const id = crypto.randomUUID();
  await env.DB.prepare(
    `INSERT INTO interactions
       (id, session_id, agent_id, timestamp, type, query, response_summary, state_change)
     VALUES (?, ?, ?, ?, 'compare_alternatives', ?, ?, ?)`
  ).bind(
    id,
    sessionId || 'no-session',
    agentId,
    new Date().toISOString(),
    caseId,
    details || '',
    claudeWasBetter ? 'claude_better' : 'external_better'
  ).run().catch(() => {});
  return id;
}

/**
 * Computes a model_usage_rate adjustment for an agent based on the
 * outcome history of its recent "compare alternatives" events.
 *
 * - If Claude wins most recent comparisons (>= 70%), nudge usage rate up
 *   (the agent is learning to trust the app).
 * - If Claude loses most recent comparisons (<= 30%), nudge usage rate
 *   down (the agent is learning the app is often not worth checking).
 * - Otherwise, no adjustment.
 *
 * The returned delta is meant to be added to the agent's
 * `model_usage_rate` (clamped to [0, 1] by the caller) and/or written to
 * `configOverrides.model_usage_rate_delta` via meeting-engine.js's
 * durable-override mechanism.
 *
 * @param {object} env
 * @param {number} agentId
 * @param {number} [sampleSize=20] - how many recent events to consider
 * @returns {Promise<{ delta: number, sample: number, claudeWinRate: number|null }>}
 */
export async function getModelUsageAdjustment(env, agentId, sampleSize = 20) {
  if (!env.DB) return { delta: 0, sample: 0, claudeWinRate: null };

  const { results } = await env.DB.prepare(
    `SELECT state_change FROM interactions
     WHERE agent_id = ? AND type = 'compare_alternatives'
     ORDER BY timestamp DESC LIMIT ?`
  ).bind(agentId, sampleSize).all();

  if (!results.length) return { delta: 0, sample: 0, claudeWinRate: null };

  const wins = results.filter((r) => r.state_change === 'claude_better').length;
  const claudeWinRate = wins / results.length;

  let delta = 0;
  if (results.length >= 5) {
    if (claudeWinRate >= 0.7) delta = 0.05;
    else if (claudeWinRate <= 0.3) delta = -0.05;
  }

  return { delta, sample: results.length, claudeWinRate };
}
