/**
 * workers/site-data.js — THE TWO DATA SURFACES OF office.avivnofar.com.
 *
 * Written 2026-08-24 (Session 16, Item B). Pure: **this module imports
 * nothing.** The same rule `owner-channel.js`, `owner-page.js`,
 * `office-policy.js` and `deliverable-lifecycle.js` keep, and for the same
 * reason — plain `node` must be able to load it so
 * `scripts/verify-site-data.js` exercises THE REAL builders rather than a
 * hand-mirror of them. Everything here takes its inputs as arguments; nothing
 * here touches `env`, D1, or the network.
 *
 * ── WHY THIS FILE EXISTS AT ALL ──────────────────────────────────────────
 *
 * `warehouse-office-AI-agents/tasks/office-site/` is a finished four-phase
 * build, 129 checks, and it cannot be deployed. Its `data.js` is generated by
 * a local Node script that shells out to `git log` in two private
 * repositories. **There is no git in a Worker.** A deployed copy would show
 * 2026-08-07 forever — including on the page whose entire purpose is telling
 * the owner what is waiting on him, which is the one thing that must never be
 * stale. So the site's first real dependency was never a page. It was a live
 * data endpoint.
 *
 * ── TWO ENDPOINTS, AND THIS IS A SECURITY BOUNDARY ───────────────────────
 *
 * Not an organisational preference. If both surfaces read one endpoint and
 * only authentication separates them, a single auth bug exposes everything.
 * **The public builder must have no path that can return internal content —
 * not hidden behind a flag, not filtered out at the end: ABSENT.**
 *
 * That is not theoretical in this estate. Eight public files naming real
 * third-party companies, in claims a service-error bug had made unreliable,
 * were removed from the public repo on 2026-08-22. And meeting transcripts —
 * which live one D1 table away from everything the public page wants — carry
 * agent names, internal blockers, task identifiers and sometimes client
 * names.
 *
 * So `buildPublicData()` and `buildAdminData()` share no code path. The
 * public builder never receives a snapshot, never receives a transcript, and
 * cannot be handed one: its signature does not accept them.
 *
 * ── WHITELIST, NEVER BLACKLIST ───────────────────────────────────────────
 *
 * `pick()` below constructs a NEW object out of NAMED KEYS. There is no
 * spread anywhere in the public path, and that absence is the mechanism:
 *
 *   A BLACKLIST FAILS OPEN THE MOMENT SOMEONE ADDS A COLUMN. A WHITELIST
 *   FAILS CLOSED.
 *
 * `scripts/verify-site-data.js` proves it rather than asserting it — it
 * poisons every source object with a field nobody whitelisted and requires
 * that the serialised public response does not contain it. That test fails if
 * a future edit replaces a pick with a spread, which is the only way this
 * property is ever going to be lost.
 *
 * And `pick()` additionally refuses any value that is not a string, a finite
 * number, a boolean or null. A whitelisted key whose value later becomes an
 * object would otherwise carry that object's whole interior through a gate
 * that only ever checked the key's NAME.
 *
 * ── WHERE THE PUBLIC FIELDS COME FROM, AND WHY THAT LINE IS DEFENSIBLE ───
 *
 * Every text field in the public response is either
 *
 *   (a) already published, in this public repo, in
 *       `config/agents-config.json` — the 13 agents' name, role, purpose and
 *       character paragraph; or
 *   (b) written in this file, by hand, to be read by strangers — the
 *       `OFFICE_MECHANISMS` block below.
 *
 * Nothing else. In particular **no D1 text column reaches the public
 * response at any point** — D1 contributes integers and nothing but
 * integers, because `cases.description`, `reports.content` and
 * `meetings.transcript` are exactly the columns that would be catastrophic
 * and are exactly the columns an aggregate query is one careless `SELECT *`
 * away from. `publicCounts()` therefore coerces every value it takes through
 * `Number()` and drops anything that does not survive it.
 *
 * The character bible is NOT a source here. It is a private root document of
 * `back-office-AI-agents` and carries a `private` classification in its own
 * header; the agents' public-facing personas come from the public config
 * instead, which is a narrower and already-published subset of the same
 * material.
 */

/* ─────────────────────────────── The gate ───────────────────────────────── */

/** A value simple enough to cross the public boundary. Anything else — an
 *  object, an array, a function, a NaN — is dropped, because a whitelist that
 *  checks only key names stops being a whitelist the day a value grows an
 *  interior. */
function scalarOrNull(v) {
  if (v === null || v === undefined) return null;
  const t = typeof v;
  if (t === 'string' || t === 'boolean') return v;
  if (t === 'number') return Number.isFinite(v) ? v : null;
  return null;
}

/**
 * Builds a NEW object holding exactly the named keys, and only scalars.
 *
 * **Never `{...src}`.** The construction is the security property: a key the
 * source grows tomorrow cannot appear here, because appearing here requires
 * someone to write its name into a whitelist constant, in this file, in a
 * commit somebody reviews.
 */
function pick(src, keys) {
  const out = {};
  const o = src && typeof src === 'object' ? src : {};
  for (const k of keys) out[k] = scalarOrNull(o[k]);
  return out;
}

/* ───────────────────────────── The whitelists ───────────────────────────── */

/**
 * The ONLY agent fields the public endpoint returns.
 *
 * Every one of these is already published in this repo's own
 * `config/agents-config.json`, which is what makes the line defensible rather
 * than a judgement call made once and forgotten.
 *
 * DELIBERATELY ABSENT, and each for its own reason rather than by oversight:
 *   model                  which provider embodies which persona. The bible's
 *                          embodiment rule shuffles this and logs it; a public
 *                          page asserting it would be wrong within a day AND
 *                          would publish the routing.
 *   durable_object_id      an internal address.
 *   topic_affinity,        the simulation's dials. "The office's mechanisms"
 *   escalation_threshold,  is a thing to EXPLAIN (see OFFICE_MECHANISMS) and
 *   quotas, states,        not a config dump — a dump is both less readable
 *   model_usage_rate, …    and more revealing.
 */
export const PUBLIC_AGENT_FIELDS = Object.freeze([
  'id', 'key', 'name', 'role', 'tier', 'clearance', 'status', 'purpose', 'character',
]);

/**
 * The ONLY aggregate counts the public endpoint returns. Integers, all of
 * them, and the names are the office's own words for what it does rather than
 * D1 table names — `cases` has held QUESTIONS since the 2026-07-18 rebuild and
 * publishing the column name would publish a four-month-stale noun.
 */
export const PUBLIC_COUNT_FIELDS = Object.freeze([
  'agents', 'questions_handled', 'reports_written', 'meetings_held',
  'interactions_logged', 'simulated_day',
]);

/**
 * Written here, by hand, to be read by a stranger. This is the office
 * explaining its own logic — which is the thing the owner actually wants a
 * visitor to see, and it is content, not a data dump.
 *
 * `OFFICE-POLICY.md` A10 governs it: *everything is shown, including
 * mistakes*, and **security findings are never published — not open, not
 * closed, not historical.** What may be shown is that the office PERFORMS
 * security review; the role and the process, never a finding or a mechanism.
 * The `security` entry below is written to that line exactly.
 */
export const OFFICE_MECHANISMS = Object.freeze([
  Object.freeze({
    id: 'roster',
    title: 'Thirteen agents, four of them ordinary',
    text: 'Nine of the thirteen are admins with a specific authority — quality, security, design, architecture, operations. Four are ordinary workers who handle the day\'s questions. The split is what makes review mean something: an admin who reviewed everything and also produced everything would be marking their own homework.',
  }),
  Object.freeze({
    id: 'state-machine',
    title: 'Mood is a state machine, not decoration',
    text: 'Each agent has a neutral state and two departures from it, entered on a scored outcome rather than at random. A good answer can push an agent into flow, where it works longer and further afield; a poor one can push it into a critical state where it re-checks and argues. The states change what the agent actually does — how long it works, how deep it follows up, how readily it escalates.',
  }),
  Object.freeze({
    id: 'review-loop',
    title: 'The delivery lifecycle is a loop with an exit, not a pipeline',
    text: 'Build, admin review, gaps raised in a meeting, discussion and where binding a vote, an improvement round, back to review. There is no cap on rounds and no round at which a thing is finished by schedule. A deliverable that passed on its first review has probably not been reviewed.',
  }),
  Object.freeze({
    id: 'improvement',
    title: 'A change to an agent is measured, then kept or dropped',
    text: 'When a reviewer changes another agent\'s working context, the change enters on probation and is measured over twenty actions — actions, not days, because weekly volume is unpredictable. Three people then decide on evidence: what changed in behaviour, what changed in quality, and whether that settles it. If the meeting does not happen the change falls, because silence must never read as approval.',
  }),
  Object.freeze({
    id: 'no-self-edit',
    title: 'No agent modifies the code that runs it',
    text: 'Not the worker, not the permission guard, not its own client module. This is the constraint the rest of the bureaucracy exists to compensate for: AI checking AI is better than nothing and is not enough, so the policy, the tests and a human\'s final approval stand in for the gap. No agent edits its own working context either — reviewers change other agents\' context, and that separation is what makes it review rather than self-rewriting.',
  }),
  Object.freeze({
    id: 'evidence',
    title: 'A claim is not evidence',
    text: 'The office is not allowed to mark its own homework. Reading a message is recorded separately from the message, against the hash of what was read, so that editing a message after it was read makes it unread again. Saying a task is done requires a line saying what was done and where it landed. Corrections to published work are appended and dated — never a silent edit, because a number that changes without explanation makes every other number unverifiable.',
  }),
  Object.freeze({
    id: 'mistakes',
    title: 'Mistakes are published',
    text: 'An office that publishes only its successes reads as public relations. What is recorded internally as a gap is published as a gap, in the same words, and disagreements between agents are published too — an office that always agrees with itself looks like one model speaking in several voices.',
  }),
  Object.freeze({
    id: 'security',
    title: 'Security review happens and is not published',
    text: 'One of the thirteen is a security specialist and every publication passes an automated scan before it leaves. What that review FINDS is never published — not open findings, not closed ones, not historical ones. A closed finding still tells a reader where to look and that the area was worth probing. So the process is shown and the findings are not, and this sentence is the whole of what the public surface says about it.',
  }),
]);

/** What the office is, in the office's own words, for a stranger. */
export const OFFICE_SUMMARY = Object.freeze({
  name: 'The Office',
  tagline: 'Thirteen AI agents that run as an office — and review each other.',
  text: 'Thirteen agents with fixed characters work a simulated year: they take questions, build things, review one another\'s work, hold meetings, vote on what is binding, and escalate what they cannot decide. Each one is played by a language model, but the character lives in a document rather than in any one model, and which model plays which persona is shuffled and logged. The interesting part is not that the agents answer questions. It is the bureaucracy around them — the review loop, the probation on changes, the refusal to let anything mark its own homework.',
  language_note: 'This page is in English. The office\'s own internal working notes are not.',
});

/* ──────────────────────── /api/public — the whole of it ──────────────────── */

/**
 * Every count coerced through `Number()`, and anything that does not survive
 * it dropped to null.
 *
 * This is the second half of "no D1 text reaches the public response". The
 * first half is that the caller passes named integers; this is the half that
 * holds even if the caller one day passes a row object straight out of a
 * `SELECT *`. A string field would arrive, fail `Number.isFinite`, and become
 * null rather than being published.
 */
export function publicCounts(raw) {
  const out = {};
  const o = raw && typeof raw === 'object' ? raw : {};
  for (const k of PUBLIC_COUNT_FIELDS) {
    const n = Number(o[k]);
    out[k] = Number.isFinite(n) ? Math.trunc(n) : null;
  }
  return out;
}

/** The 13 personas, reduced to the whitelist. Order is by id, stably. */
export function publicAgents(agents) {
  const list = Array.isArray(agents) ? agents : [];
  return list
    .map((a) => pick(a, PUBLIC_AGENT_FIELDS))
    .filter((a) => a.id !== null && a.name)
    .sort((a, b) => Number(a.id) - Number(b.id));
}

/**
 * THE PUBLIC RESPONSE. No authentication, so this is the field list a stranger
 * gets, and the signature is the security argument: it takes agents and
 * integers. There is no parameter through which a snapshot, a transcript, a
 * board task or an owner message could reach it, so no bug inside it can
 * publish one.
 *
 * @param {object}   input
 * @param {object[]} input.agents      config/agents-config.json's `agents`
 * @param {object}   input.counts      named integers only
 * @param {string}   input.generatedAt ISO string, supplied by the caller so
 *                                     this module makes no clock call and the
 *                                     verifier can pin it
 */
export function buildPublicData({ agents = [], counts = {}, generatedAt = null } = {}) {
  return {
    ok: true,
    surface: 'public',
    generated_at: typeof generatedAt === 'string' ? generatedAt : null,
    office: OFFICE_SUMMARY,
    mechanisms: OFFICE_MECHANISMS,
    agents: publicAgents(agents),
    counts: publicCounts(counts),
    // Said out loud on the surface itself, so a reader knows what they are
    // looking at rather than inferring completeness from what is present.
    // A10 again: the gaps are content.
    notes: Object.freeze([
      'These counts come from the office\'s live database. They are totals since the simulation began on 2026-06-17.',
      'The office\'s internal working material — meeting transcripts, its task board, its correspondence with its owner — is not served here and is not reachable from this endpoint.',
      'Each agent\'s character text is the office\'s own published configuration, not a summary written for this page.',
    ]),
  };
}

/* ──────────────────────── /api/admin — the full picture ─────────────────── */

/**
 * THE CONTRACT THIS SHAPE MATCHES, recorded 2026-08-24 by reading
 * `warehouse-office-AI-agents/tasks/office-site/data.js` (read-only) and its
 * generator:
 *
 *   window.OFFICE_SITE_DATA = {
 *     generated_at, generated_by,
 *     agents:        [{ id, slug, name, title, role, purpose, live,
 *                       has_persona, produced[], bible_detail{…} }],
 *     pending_items: [{ id, kind, title, source, detail, status_note }],
 *     activity:      [{ kind, repo, sha, short_sha, date, sort_key, author,
 *                       message }  |  { kind:'session_record', … }],
 *     data_gaps:     [ string ],
 *   }
 *
 * The keys above are reproduced exactly so the existing built site consumes
 * this without being rewritten. **Two of them are honestly empty here and say
 * so in `data_gaps` rather than being quietly dropped:**
 *
 *   bible_detail  the character bible is a private root document of
 *                 back-office-AI-agents. The Worker does not fetch it. The
 *                 built site already has it baked into its own data.js and it
 *                 does not go stale, so serving it live would be work for no
 *                 freshness. `null`, and named as null.
 *   produced      a directory inventory of each agent's campus folder. That
 *                 is a filesystem walk of a private repo; the Worker has no
 *                 filesystem and would need one API call per agent per folder.
 *                 `[]`, and named as empty.
 *
 * The two the site actually needs LIVE — `pending_items` and `activity` — are
 * live, and they are the two that were frozen at 2026-08-07.
 */
export const ADMIN_CONTRACT_KEYS = Object.freeze([
  'generated_at', 'generated_by', 'agents', 'pending_items', 'activity', 'data_gaps',
]);

/** `slug` in the site's contract is `NN-the-name`, matching the campus folder
 *  names. Derived from the config key (`agent-1-perfectionist`) rather than
 *  stored twice — two spellings of one identifier is drift waiting to happen. */
export function agentSlug(agent) {
  const id = Number(agent?.id);
  const key = String(agent?.key || '');
  const m = /^agent-\d+-(.+)$/.exec(key);
  if (!Number.isFinite(id) || !m) return null;
  return `${String(id).padStart(2, '0')}-the-${m[1].replace(/^the-/, '')}`;
}

/**
 * The board, the open questions and the submissions ledger, folded into the
 * site's one `pending_items` shape.
 *
 * WHAT COUNTS AS PENDING, stated rather than implied: a board task the office
 * cannot start (NOT-READY or BLOCKED), a question the office asked the owner
 * that has no answer, and a submission awaiting his decision. A READY task is
 * the office's own work and is not waiting on him; including it would make the
 * list longer and less true.
 */
export function buildPendingItems(snapshot) {
  const items = [];
  const tasks = snapshot?.board?.tasks || [];
  for (const t of tasks) {
    if (t.state !== 'NOT-READY' && t.state !== 'BLOCKED') continue;
    items.push({
      id: `board-${String(t.id || '').toLowerCase()}`,
      kind: t.state === 'BLOCKED' ? 'blocked' : 'decision',
      title: t.title || t.id || null,
      source: `campus/shared/board/BOARD.md, ${t.id}, ${t.state}`,
      detail: t.blockedBy ? `Blocked by: ${t.blockedBy}` : 'No "Blocked by" line — the board does not say what this is waiting on.',
      status_note: t.stage ? `Lifecycle stage: ${t.stage}` : null,
    });
  }

  const questions = snapshot?.questions?.questions || [];
  for (const q of questions) {
    if (!q.open) continue;
    items.push({
      id: `question-${String(q.id || '').toLowerCase()}`,
      kind: 'question',
      title: q.title || q.question || q.id || null,
      source: `channel/to-owner/OPEN-QUESTIONS.md, ${q.id}`,
      detail: q.fallback ? `If no answer comes: ${q.fallback}` : 'No fallback recorded — the office did not say what it will do without an answer.',
      status_note: q.date ? `Asked ${q.date}` : null,
    });
  }

  const submissions = snapshot?.submissions?.submissions || [];
  for (const s of submissions) {
    if (!s.open) continue;
    items.push({
      id: `submission-${String(s.id || '').toLowerCase()}`,
      kind: 'approval',
      title: s.title || s.id || null,
      source: `channel/to-owner/SUBMISSIONS.md, ${s.id}`,
      detail: s.recommend ? `The office recommends: ${s.recommend}` : (s.did || 'No recommendation recorded.'),
      status_note: s.escalation?.rung ? `${s.escalation.rung}${s.escalation.days != null ? ` — ${s.escalation.days} days open` : ''}` : null,
    });
  }

  return items;
}

/**
 * Recent office activity from D1 — reports written and meetings held.
 *
 * **NO TRANSCRIPTS AND NO REPORT BODIES.** The caller selects titles and
 * timestamps; this maps them. `meetings.transcript` and `reports.content` are
 * the two columns this estate most needs never to leak, and the way they do
 * not leak is that nothing selects them.
 *
 * NOT INCLUDED, and named in `data_gaps` rather than silently absent: the git
 * commit feed. `data.js` built it by shelling out to `git log` in two private
 * repos, which is precisely what a Worker cannot do and precisely why that
 * file froze. Reproducing it would mean paginating two GitHub Contents APIs on
 * every page load. It is a real gap; it is not a pretended one.
 */
export function buildActivity({ reports = [], meetings = [] } = {}) {
  const out = [];
  for (const r of reports) {
    out.push({
      kind: 'report',
      repo: null,
      date: r.created_at || null,
      sort_key: r.created_at || '',
      agent_id: Number.isFinite(Number(r.agent_id)) ? Number(r.agent_id) : null,
      type: r.type || null,
      severity: r.severity || null,
      message: r.title || null,
    });
  }
  for (const m of meetings) {
    out.push({
      kind: 'meeting',
      repo: null,
      date: m.created_at || null,
      sort_key: m.created_at || '',
      agent_id: null,
      type: m.type || null,
      severity: null,
      message: `${m.type || 'meeting'} — ${m.attendee_count ?? '?'} attending`,
    });
  }
  return out.sort((a, b) => String(b.sort_key).localeCompare(String(a.sort_key)));
}

/**
 * THE ADMIN RESPONSE. Authenticated. Full data.
 *
 * `errors` is carried through rather than swallowed, and that is the same
 * judgement `buildOwnerState()` made for the same reason: a surface that
 * silently omitted the office's own read errors would be the most misleading
 * one in the system — the owner would read an empty pending list as "nothing
 * is waiting on me" when the truth was "the office could not read its board".
 */
export function buildAdminData({
  agents = [], counts = {}, snapshot = null,
  reports = [], meetings = [], generatedAt = null, versionId = null,
} = {}) {
  const list = Array.isArray(agents) ? agents : [];
  const snapshotReadable = !!(snapshot && (snapshot.board || snapshot.requirements));

  return {
    ok: true,
    surface: 'admin',
    generated_at: typeof generatedAt === 'string' ? generatedAt : null,
    generated_by: `site-data.js (live, Worker version ${versionId || 'unknown'})`,
    agents: list.map((a) => ({
      id: Number(a.id),
      slug: agentSlug(a),
      name: a.name || null,
      title: `AGENT ${a.id} — ${String(a.name || '').toUpperCase()}`,
      role: a.role || null,
      purpose: a.purpose || null,
      character: a.character || null,
      tier: a.tier || null,
      clearance: a.clearance || null,
      status: a.status || null,
      live: a.status === 'active',
      has_persona: !!a.character,
      // Named, not omitted — see ADMIN_CONTRACT_KEYS' note.
      produced: [],
      bible_detail: null,
    })),
    counts: publicCounts(counts),
    pending_items: buildPendingItems(snapshot),
    activity: buildActivity({ reports, meetings }),
    // The office's own errors reading its own files. Reported, never hidden.
    errors: Array.isArray(snapshot?.errors) ? snapshot.errors : [],
    data_gaps: [
      snapshotReadable
        ? 'pending_items is live: the board, the open questions and the submissions ledger, read from back-office at request time.'
        : 'THE OFFICE COULD NOT READ ITS OWN BOARD. pending_items is empty because the read failed, NOT because nothing is pending — see `errors`.',
      'bible_detail is null. The character bible is a private root document and the Worker does not fetch it; the built site carries its own copy, which does not go stale.',
      'produced is empty. It is a directory inventory of each agent\'s campus folder — a filesystem walk of a private repo, which a Worker has no filesystem to perform.',
      'activity carries reports and meetings from the office\'s database, with NO report bodies and NO meeting transcripts — those columns are never selected.',
      'activity does NOT carry the git commit feed. data.js built that by shelling out to `git log` in two private repos, which is exactly what a Worker cannot do and exactly why that file froze on 2026-08-07.',
      'Counts are totals since the simulation began on 2026-06-17, not per-day figures.',
    ],
  };
}
