/**
 * workers/site-data.js — THE TWO DATA SURFACES OF office.avivnofar.com.
 *
 * Written 2026-08-24 (Session 16, Item B). Pure: **this module imports
 * nothing.** The same rule `owner-channel.js`, `owner-page.js`,
 * `office-policy.js` and `deliverable-lifecycle.js` keep, and for the same
 * reason — plain `node` must be able to load it so
 * `scripts/verify-site-data.js` exercises THE REAL builders rather than a
 * hand-mirror of them. Everything here takes its inputs as arguments; nothing
 * here touches `env`, D1, or the network.
 *
 * ── WHY THIS FILE EXISTS AT ALL ──────────────────────────────────────────
 *
 * `warehouse-office-AI-agents/tasks/office-site/` is a finished four-phase
 * build, 129 checks, and it cannot be deployed. Its `data.js` is generated by
 * a local Node script that shells out to `git log` in two private
 * repositories. **There is no git in a Worker.** A deployed copy would show
 * 2026-08-07 forever — including on the page whose entire purpose is telling
 * the owner what is waiting on him, which is the one thing that must never be
 * stale. So the site's first real dependency was never a page. It was a live
 * data endpoint.
 *
 * ── TWO ENDPOINTS, AND THIS IS A SECURITY BOUNDARY ───────────────────────
 *
 * Not an organisational preference. If both surfaces read one endpoint and
 * only authentication separates them, a single auth bug exposes everything.
 * **The public builder must have no path that can return internal content —
 * not hidden behind a flag, not filtered out at the end: ABSENT.**
 *
 * That is not theoretical in this estate. Eight public files naming real
 * third-party companies, in claims a service-error bug had made unreliable,
 * were removed from the public repo on 2026-08-22. And meeting transcripts —
 * which live one D1 table away from everything the public page wants — carry
 * agent names, internal blockers, task identifiers and sometimes client
 * names.
 *
 * So `buildPublicData()` and `buildAdminData()` share no code path. The
 * public builder never receives a snapshot, never receives a transcript, and
 * cannot be handed one: its signature does not accept them.
 *
 * ── WHITELIST, NEVER BLACKLIST ───────────────────────────────────────────
 *
 * `pick()` below constructs a NEW object out of NAMED KEYS. There is no
 * spread anywhere in the public path, and that absence is the mechanism:
 *
 *   A BLACKLIST FAILS OPEN THE MOMENT SOMEONE ADDS A COLUMN. A WHITELIST
 *   FAILS CLOSED.
 *
 * `scripts/verify-site-data.js` proves it rather than asserting it — it
 * poisons every source object with a field nobody whitelisted and requires
 * that the serialised public response does not contain it. That test fails if
 * a future edit replaces a pick with a spread, which is the only way this
 * property is ever going to be lost.
 *
 * And `pick()` additionally refuses any value that is not a string, a finite
 * number, a boolean or null. A whitelisted key whose value later becomes an
 * object would otherwise carry that object's whole interior through a gate
 * that only ever checked the key's NAME.
 *
 * ── WHERE THE PUBLIC FIELDS COME FROM, AND WHY THAT LINE IS DEFENSIBLE ───
 *
 * Every text field in the public response is either
 *
 *   (a) already published, in this public repo, in
 *       `config/agents-config.json` — the 13 agents' name, role, purpose and
 *       character paragraph; or
 *   (b) written in this file, by hand, to be read by strangers — the
 *       `OFFICE_MECHANISMS` block below.
 *
 * Nothing else. In particular **no D1 text column reaches the public
 * response at any point** — D1 contributes integers and nothing but
 * integers, because `cases.description`, `reports.content` and
 * `meetings.transcript` are exactly the columns that would be catastrophic
 * and are exactly the columns an aggregate query is one careless `SELECT *`
 * away from. `publicCounts()` therefore coerces every value it takes through
 * `Number()` and drops anything that does not survive it.
 *
 * The character bible is NOT a source here. It is a private root document of
 * `back-office-AI-agents` and carries a `private` classification in its own
 * header; the agents' public-facing personas come from the public config
 * instead, which is a narrower and already-published subset of the same
 * material.
 */

/* ─────────────────────────────── The gate ───────────────────────────────── */

/** A value simple enough to cross the public boundary. Anything else — an
 *  object, an array, a function, a NaN — is dropped, because a whitelist that
 *  checks only key names stops being a whitelist the day a value grows an
 *  interior. */
function scalarOrNull(v) {
  if (v === null || v === undefined) return null;
  const t = typeof v;
  if (t === 'string' || t === 'boolean') return v;
  if (t === 'number') return Number.isFinite(v) ? v : null;
  return null;
}

/**
 * Builds a NEW object holding exactly the named keys, and only scalars.
 *
 * **Never `{...src}`.** The construction is the security property: a key the
 * source grows tomorrow cannot appear here, because appearing here requires
 * someone to write its name into a whitelist constant, in this file, in a
 * commit somebody reviews.
 */
function pick(src, keys) {
  const out = {};
  const o = src && typeof src === 'object' ? src : {};
  for (const k of keys) out[k] = scalarOrNull(o[k]);
  return out;
}

/* ───────────────────────────── The whitelists ───────────────────────────── */

/**
 * The ONLY agent fields the public endpoint returns.
 *
 * Every one of these is already published in this repo's own
 * `config/agents-config.json`, which is what makes the line defensible rather
 * than a judgement call made once and forgotten.
 *
 * DELIBERATELY ABSENT, and each for its own reason rather than by oversight:
 *   model                  which provider embodies which persona. The bible's
 *                          embodiment rule shuffles this and logs it; a public
 *                          page asserting it would be wrong within a day AND
 *                          would publish the routing.
 *   durable_object_id      an internal address.
 *   topic_affinity,        the simulation's dials. "The office's mechanisms"
 *   escalation_threshold,  is a thing to EXPLAIN (see OFFICE_MECHANISMS) and
 *   quotas, states,        not a config dump — a dump is both less readable
 *   model_usage_rate, …    and more revealing.
 */
export const PUBLIC_AGENT_FIELDS = Object.freeze([
  'id', 'key', 'name', 'role', 'tier', 'clearance', 'status', 'purpose', 'character',
]);

/**
 * The ONLY aggregate counts the public endpoint returns. Integers, all of
 * them, and the names are the office's own words for what it does rather than
 * D1 table names — `cases` has held QUESTIONS since the 2026-07-18 rebuild and
 * publishing the column name would publish a four-month-stale noun.
 */
export const PUBLIC_COUNT_FIELDS = Object.freeze([
  'agents', 'questions_handled', 'reports_written', 'meetings_held',
  'interactions_logged', 'simulated_day',
]);

/**
 * Written here, by hand, to be read by a stranger. This is the office
 * explaining its own logic — which is the thing the owner actually wants a
 * visitor to see, and it is content, not a data dump.
 *
 * `OFFICE-POLICY.md` A10 governs it: *everything is shown, including
 * mistakes*, and **security findings are never published — not open, not
 * closed, not historical.** What may be shown is that the office PERFORMS
 * security review; the role and the process, never a finding or a mechanism.
 * The `security` entry below is written to that line exactly.
 */
export const OFFICE_MECHANISMS = Object.freeze([
  Object.freeze({
    id: 'roster',
    title: 'Thirteen agents, four of them ordinary',
    text: 'Nine of the thirteen are admins with a specific authority — quality, security, design, architecture, operations. Four are ordinary workers who handle the day\'s questions. The split is what makes review mean something: an admin who reviewed everything and also produced everything would be marking their own homework.',
  }),
  Object.freeze({
    id: 'state-machine',
    title: 'Mood is a state machine, not decoration',
    text: 'Each agent has a neutral state and two departures from it, entered on a scored outcome rather than at random. A good answer can push an agent into flow, where it works longer and further afield; a poor one can push it into a critical state where it re-checks and argues. The states change what the agent actually does — how long it works, how deep it follows up, how readily it escalates.',
  }),
  Object.freeze({
    id: 'review-loop',
    title: 'The delivery lifecycle is a loop with an exit, not a pipeline',
    text: 'Build, admin review, gaps raised in a meeting, discussion and where binding a vote, an improvement round, back to review. There is no cap on rounds and no round at which a thing is finished by schedule. A deliverable that passed on its first review has probably not been reviewed.',
  }),
  Object.freeze({
    id: 'improvement',
    title: 'A change to an agent is measured, then kept or dropped',
    text: 'When a reviewer changes another agent\'s working context, the change enters on probation and is measured over twenty actions — actions, not days, because weekly volume is unpredictable. Three people then decide on evidence: what changed in behaviour, what changed in quality, and whether that settles it. If the meeting does not happen the change falls, because silence must never read as approval.',
  }),
  Object.freeze({
    id: 'no-self-edit',
    title: 'No agent modifies the code that runs it',
    text: 'Not the worker, not the permission guard, not its own client module. This is the constraint the rest of the bureaucracy exists to compensate for: AI checking AI is better than nothing and is not enough, so the policy, the tests and a human\'s final approval stand in for the gap. No agent edits its own working context either — reviewers change other agents\' context, and that separation is what makes it review rather than self-rewriting.',
  }),
  Object.freeze({
    id: 'evidence',
    title: 'A claim is not evidence',
    text: 'The office is not allowed to mark its own homework. Reading a message is recorded separately from the message, against the hash of what was read, so that editing a message after it was read makes it unread again. Saying a task is done requires a line saying what was done and where it landed. Corrections to published work are appended and dated — never a silent edit, because a number that changes without explanation makes every other number unverifiable.',
  }),
  Object.freeze({
    id: 'mistakes',
    title: 'Mistakes are published',
    text: 'An office that publishes only its successes reads as public relations. What is recorded internally as a gap is published as a gap, in the same words, and disagreements between agents are published too — an office that always agrees with itself looks like one model speaking in several voices.',
  }),
  Object.freeze({
    id: 'security',
    title: 'Security review happens and is not published',
    text: 'One of the thirteen is a security specialist and every publication passes an automated scan before it leaves. What that review FINDS is never published — not open findings, not closed ones, not historical ones. A closed finding still tells a reader where to look and that the area was worth probing. So the process is shown and the findings are not, and this sentence is the whole of what the public surface says about it.',
  }),
]);

/** What the office is, in the office's own words, for a stranger. */
export const OFFICE_SUMMARY = Object.freeze({
  name: 'The Office',
  tagline: 'Thirteen AI agents that run as an office — and review each other.',
  text: 'Thirteen agents with fixed characters work a simulated year: they take questions, build things, review one another\'s work, hold meetings, vote on what is binding, and escalate what they cannot decide. Each one is played by a language model, but the character lives in a document rather than in any one model, and which model plays which persona is shuffled and logged. The interesting part is not that the agents answer questions. It is the bureaucracy around them — the review loop, the probation on changes, the refusal to let anything mark its own homework.',
  language_note: 'This page is in English. The office\'s own internal working notes are not.',
});

/* ──────────────────────── /api/public — the whole of it ──────────────────── */

/**
 * Every count coerced through `Number()`, and anything that does not survive
 * it dropped to null.
 *
 * This is the second half of "no D1 text reaches the public response". The
 * first half is that the caller passes named integers; this is the half that
 * holds even if the caller one day passes a row object straight out of a
 * `SELECT *`. A string field would arrive, fail `Number.isFinite`, and become
 * null rather than being published.
 */
export function publicCounts(raw) {
  const out = {};
  const o = raw && typeof raw === 'object' ? raw : {};
  for (const k of PUBLIC_COUNT_FIELDS) {
    const n = Number(o[k]);
    out[k] = Number.isFinite(n) ? Math.trunc(n) : null;
  }
  return out;
}

/** The 13 personas, reduced to the whitelist. Order is by id, stably. */
export function publicAgents(agents) {
  const list = Array.isArray(agents) ? agents : [];
  return list
    .map((a) => pick(a, PUBLIC_AGENT_FIELDS))
    .filter((a) => a.id !== null && a.name)
    .sort((a, b) => Number(a.id) - Number(b.id));
}

/**
 * THE PUBLIC RESPONSE. No authentication, so this is the field list a stranger
 * gets, and the signature is the security argument: it takes agents and
 * integers. There is no parameter through which a snapshot, a transcript, a
 * board task or an owner message could reach it, so no bug inside it can
 * publish one.
 *
 * @param {object}   input
 * @param {object[]} input.agents      config/agents-config.json's `agents`
 * @param {object}   input.counts      named integers only
 * @param {string}   input.generatedAt ISO string, supplied by the caller so
 *                                     this module makes no clock call and the
 *                                     verifier can pin it
 */
export function buildPublicData({ agents = [], counts = {}, generatedAt = null } = {}) {
  return {
    ok: true,
    surface: 'public',
    generated_at: typeof generatedAt === 'string' ? generatedAt : null,
    office: OFFICE_SUMMARY,
    mechanisms: OFFICE_MECHANISMS,
    agents: publicAgents(agents),
    counts: publicCounts(counts),
    // Said out loud on the surface itself, so a reader knows what they are
    // looking at rather than inferring completeness from what is present.
    // A10 again: the gaps are content.
    notes: Object.freeze([
      'These counts come from the office\'s live database. They are totals since the simulation began on 2026-06-17.',
      'The office\'s internal working material — meeting transcripts, its task board, its correspondence with its owner — is not served here and is not reachable from this endpoint.',
      'Each agent\'s character text is the office\'s own published configuration, not a summary written for this page.',
    ]),
  };
}

/* ──────────────────────── /api/admin — the full picture ─────────────────── */

/**
 * THE CONTRACT THIS SHAPE MATCHES, recorded 2026-08-24 by reading
 * `warehouse-office-AI-agents/tasks/office-site/data.js` (read-only) and its
 * generator:
 *
 *   window.OFFICE_SITE_DATA = {
 *     generated_at, generated_by,
 *     agents:        [{ id, slug, name, title, role, purpose, live,
 *                       has_persona, produced[], bible_detail{…} }],
 *     pending_items: [{ id, kind, title, source, detail, status_note }],
 *     activity:      [{ kind, repo, sha, short_sha, date, sort_key, author,
 *                       message }  |  { kind:'session_record', … }],
 *     data_gaps:     [ string ],
 *   }
 *
 * The keys above are reproduced exactly so the existing built site consumes
 * this without being rewritten. **Two of them are honestly empty here and say
 * so in `data_gaps` rather than being quietly dropped:**
 *
 *   bible_detail  the character bible is a private root document of
 *                 back-office-AI-agents. The Worker does not fetch it. The
 *                 built site already has it baked into its own data.js and it
 *                 does not go stale, so serving it live would be work for no
 *                 freshness. `null`, and named as null.
 *   produced      a directory inventory of each agent's campus folder. That
 *                 is a filesystem walk of a private repo; the Worker has no
 *                 filesystem and would need one API call per agent per folder.
 *                 `[]`, and named as empty.
 *
 * The two the site actually needs LIVE — `pending_items` and `activity` — are
 * live, and they are the two that were frozen at 2026-08-07.
 */
export const ADMIN_CONTRACT_KEYS = Object.freeze([
  'generated_at', 'generated_by', 'agents', 'pending_items', 'activity', 'data_gaps',
]);

/** `slug` in the site's contract is `NN-the-name`, matching the campus folder
 *  names. Derived from the config key (`agent-1-perfectionist`) rather than
 *  stored twice — two spellings of one identifier is drift waiting to happen. */
export function agentSlug(agent) {
  const id = Number(agent?.id);
  const key = String(agent?.key || '');
  const m = /^agent-\d+-(.+)$/.exec(key);
  if (!Number.isFinite(id) || !m) return null;
  return `${String(id).padStart(2, '0')}-the-${m[1].replace(/^the-/, '')}`;
}

/**
 * The board, the open questions and the submissions ledger, folded into the
 * site's one `pending_items` shape.
 *
 * WHAT COUNTS AS PENDING, stated rather than implied: a board task the office
 * cannot start (NOT-READY or BLOCKED), a question the office asked the owner
 * that has no answer, and a submission awaiting his decision. A READY task is
 * the office's own work and is not waiting on him; including it would make the
 * list longer and less true.
 */
/* ── THE THREE-PART SHAPE, AND WHY IT IS NOT WRITTEN AGAIN HERE ──────────
 *
 * Added 2026-08-25 (Session 18, Item B). The office already composes what a
 * person needs in order to answer — `noticeParts()` in `owner-notify.js`: the
 * ASK with the board identifiers stripped out of it, the OPTIONS with what each
 * one means, and WHAT HAPPENS IF HE SAYS NOTHING. That composition is what goes
 * into his email and into every Issue.
 *
 * It is INJECTED rather than imported, because this module imports nothing (see
 * the file header) and `owner-notify.js` imports nothing either — so the caller
 * passes the function in and there is exactly one implementation of the shape.
 * A9's argument, applied to a sentence instead of a document: *copies diverge.*
 *
 * When it is NOT passed, `notice` is null and `data_gaps` says so. It does not
 * fall back to a second composition written here — a fallback shape is the
 * divergence this arrangement exists to prevent, and it would be invisible.
 */

/** Board identifiers, so the visible ask never carries one. Matches
 *  `owner-notify.js`'s ID_PATTERN — the same list, because it is the same job
 *  and this module cannot import it. */
const VISIBLE_ID_PATTERN = /\b(?:OB|S|REQ|C|AD|KFM|R|OQ)-\d+\b/g;

function stripIdsForDisplay(text) {
  if (!text) return '';
  return String(text)
    .replace(VISIBLE_ID_PATTERN, '')
    .replace(/\(\s*\)|\[\s*\]/g, '')
    .replace(/\s{2,}/g, ' ')
    .replace(/\s+([.,;:])/g, '$1')
    .replace(/^[\s—–-]+/, '')
    .trim();
}

/**
 * The other half of the identifier problem, and the office already learned this
 * one the hard way.
 *
 * `stripOfficeIds()` DELETES. That is right for the ask — one short sentence
 * that survives the removal — and it was wrong everywhere else: Issue #47 went
 * out reading *"sequenced against 's one finished, polished product"* because
 * an id was deleted from the middle of a sentence. `owner-notify.js` records
 * the correction: only the ask is stripped, everything below it is quoted as
 * the office wrote it.
 *
 * But the office's own prose DOES name items — *"Blocked by: OB-001. Flow
 * analysis before the call audit…"* — and a card that shows a person `OB-001`
 * is asking him to look something up he has never agreed to learn.
 *
 * So this SUBSTITUTES instead of deleting: a noun phrase for a noun phrase. The
 * sentence still reads, and nothing in it asks him to decode an identifier.
 * *"Blocked by another item on the board. Flow analysis before…"*
 */
const ID_PLAIN_LANGUAGE = [
  [/`?\bOB-\d+`?/g, 'another item on the board'],
  [/`?\b(?:Q|OQ)-\d+`?/g, 'an open question'],
  [/`?\bS-\d+`?/g, 'a submission awaiting your decision'],
  [/`?\bREQ-\d+`?/g, 'a client requirement'],
  [/`?\b(?:C|AD|KFM|R)-\d+`?/g, 'another recorded item'],
];

export function plainOfficeIds(text) {
  if (!text) return text === 0 ? '0' : null;
  let out = String(text);
  for (const [pattern, phrase] of ID_PLAIN_LANGUAGE) out = out.replace(pattern, phrase);
  return out.replace(/\s{2,}/g, ' ').trim();
}

/**
 * CAN AN ANSWER TYPED ON THIS PAGE STOP THE OFFICE ASKING?
 *
 * This is not a presentational detail. `owner-channel.js`'s `itemIdsInText()`
 * is what turns a file the owner wrote into "he has acted on this item", and it
 * matches `S-NNN` and `Q-NNN` — three digits, and deliberately NOT `OB-NNN`,
 * because a board task is the office's own work and is not a thing he is being
 * asked to decide in the channel.
 *
 * So the same expression is applied here, and the answer is carried to the page
 * as `answer_stops_the_asking`. An item where it is false gets told so on the
 * card, in words. **The failure this replaces is the owner answering on a page
 * and being emailed the same item the next morning** — and a page that implied
 * every answer silences every item would have reproduced it for board tasks
 * while fixing it for everything else, which is worse than not claiming it.
 */
const CHANNEL_ITEM_ID = /^[SQ]-\d{3}$/;

export function answerStopsTheAsking(itemId) {
  return CHANNEL_ITEM_ID.test(String(itemId || ''));
}

/**
 * The board, the open questions and the submissions ledger, folded into the
 * site's one `pending_items` shape.
 *
 * WHAT COUNTS AS PENDING, stated rather than implied: a board task the office
 * cannot start (NOT-READY or BLOCKED), a question the office asked the owner
 * that has no answer, and a submission awaiting his decision. A READY task is
 * the office's own work and is not waiting on him; including it would make the
 * list longer and less true.
 *
 * @param {object} snapshot
 * @param {object} [deps]
 * @param {function} [deps.noticeParts] `owner-notify.js`'s composer, injected.
 */
export function buildPendingItems(snapshot, { noticeParts = null } = {}) {
  const items = [];

  /** The three parts, composed by the office's own composer or not at all. */
  const notice = (item) => {
    if (typeof noticeParts !== 'function') return null;
    const parts = noticeParts(item);
    return {
      ask: parts.ask || null,
      options: parts.options || [],
      no_answer: parts.noAnswer || null,
      // What the office could NOT state. Shown, not hidden: an item with no
      // recorded default is one where the office does not know what it will do
      // if he stays quiet, and that is the most important thing on the card.
      missing: parts.missing || [],
      complete: !!parts.ok,
    };
  };

  const tasks = snapshot?.board?.tasks || [];
  for (const t of tasks) {
    const id = String(t.id || '');
    if (t.state !== 'NOT-READY' && t.state !== 'BLOCKED') continue;
    items.push({
      id: `board-${id.toLowerCase()}`,
      item_id: id || null,
      kind: t.state === 'BLOCKED' ? 'blocked' : 'decision',
      title: t.title || t.id || null,
      ask: stripIdsForDisplay(t.title || ''),
      // The visible provenance, in words. `source` below keeps the identifier
      // for the record; this is the line a person reads.
      source_plain: t.state === 'BLOCKED'
        ? 'On the office\'s task board, blocked — it cannot start this until something is resolved.'
        : 'On the office\'s task board, not ready to start — something about it is still undecided.',
      source: `campus/shared/board/BOARD.md, ${t.id}, ${t.state}`,
      detail: t.blockedBy ? `Blocked by: ${t.blockedBy}` : 'No "Blocked by" line — the board does not say what this is waiting on.',
      // What the CARD shows. `detail` above keeps the office's own words for
      // the record; this is the same sentence with the identifiers said in
      // English. See plainOfficeIds().
      detail_plain: t.blockedBy
        ? `Blocked by ${plainOfficeIds(t.blockedBy)}`
        : 'The board does not say what this is waiting on — there is no "blocked by" line on it.',
      status_note: t.stage ? `Lifecycle stage: ${t.stage}` : null,
      status_note_plain: t.stage ? `Where it is in the office's own lifecycle: ${plainOfficeIds(t.stage)}` : null,
      by_when: null,
      notice: notice({ title: t.title, decision: t.title, recommend: null, fallback: null }),
      answer_kind: 'instruction',
      answer_stops_the_asking: answerStopsTheAsking(id),
      answer_note: 'This is the office\'s own work, not a question in the channel — an answer here is filed as an'
        + ' instruction and reaches every agent\'s prompt, but the office does not record it as a decision against'
        + ' this board item and nothing here will mark the item answered.',
    });
  }

  const questions = snapshot?.questions?.questions || [];
  for (const q of questions) {
    if (!q.open) continue;
    const id = String(q.id || '');
    const asked = q.title || q.question || q.id || null;
    items.push({
      id: `question-${id.toLowerCase()}`,
      item_id: id || null,
      kind: 'question',
      title: asked,
      ask: stripIdsForDisplay(asked || ''),
      source_plain: 'A question the office asked you and cannot answer itself.',
      source: `channel/to-owner/OPEN-QUESTIONS.md, ${q.id}`,
      detail: q.fallback ? `If no answer comes: ${q.fallback}` : 'No fallback recorded — the office did not say what it will do without an answer.',
      detail_plain: q.fallback ? `If no answer comes: ${plainOfficeIds(q.fallback)}` : 'No fallback recorded — the office did not say what it will do without an answer.',
      status_note: q.date ? `Asked ${q.date}` : null,
      status_note_plain: q.date ? `Asked ${q.date}` : null,
      by_when: escalationSentence(q),
      notice: notice({
        title: asked,
        decision: q.need ? `${q.need} — blocking: ${q.blocking || 'unstated'}` : (q.blocking || asked),
        recommend: null,
        fallback: q.fallback,
      }),
      answer_kind: 'decision',
      answer_stops_the_asking: answerStopsTheAsking(id),
      answer_note: null,
    });
  }

  const submissions = snapshot?.submissions?.submissions || [];
  for (const s of submissions) {
    if (!s.open) continue;
    const id = String(s.id || '');
    items.push({
      id: `submission-${id.toLowerCase()}`,
      item_id: id || null,
      kind: 'approval',
      title: s.title || s.id || null,
      ask: stripIdsForDisplay(s.title || ''),
      source_plain: 'Work the office finished and submitted to you — it is waiting on your decision to go further.',
      source: `channel/to-owner/SUBMISSIONS.md, ${s.id}`,
      detail: s.recommend ? `The office recommends: ${s.recommend}` : (s.did || 'No recommendation recorded.'),
      detail_plain: s.recommend
        ? `The office recommends: ${plainOfficeIds(s.recommend)}`
        : (plainOfficeIds(s.did) || 'No recommendation recorded.'),
      status_note: s.escalation?.rung ? `${s.escalation.rung}${s.escalation.days != null ? ` — ${s.escalation.days} days open` : ''}` : null,
      status_note_plain: s.escalation?.rung ? `${s.escalation.rung}${s.escalation.days != null ? ` — ${s.escalation.days} days open` : ''}` : null,
      by_when: escalationSentence(s),
      notice: notice({
        title: s.title,
        decision: s.decision || s.title,
        recommend: s.recommend,
        fallback: s.fallback,
      }),
      answer_kind: 'decision',
      answer_stops_the_asking: answerStopsTheAsking(id),
      answer_note: null,
    });
  }

  return items;
}

/**
 * "…and by when", in words, from the age ladder the channel already runs.
 *
 * Returns null rather than inventing a deadline where the office has not
 * recorded one. A made-up date on this page would be the single most
 * misleading thing on it.
 */
export function escalationSentence(entry) {
  const esc = entry?.escalation;
  if (!esc) return null;
  const days = Number.isFinite(Number(esc.days)) ? Number(esc.days) : null;
  const rung = esc.rung || null;
  if (esc.takeFallback) {
    return `The office has ALREADY taken its default on this (14 days or more). ${rung ? rung + '. ' : ''}`
      + 'The entry stays open and it keeps asking, so an answer now still changes what happens next.';
  }
  if (rung && days !== null) return `${rung} — ${days} day(s) with no answer.`;
  if (rung) return rung;
  if (days !== null) return `${days} day(s) with no answer.`;
  return null;
}

/* ────────────────── the office's clockwork, as a list ────────────────────── */

/**
 * The office's own labels are paragraphs — several of them carry an entire
 * incident write-up (`MOVED OFF THE 08:00 TICK on 2026-08-16 (OB-074): it
 * shared 08:00 with…`). That history belongs in the config file where it is,
 * not on a page. This takes the first sentence and says nothing else.
 */
export function firstSentence(text, max = 180) {
  const s = String(text || '').replace(/\s+/g, ' ').trim();
  if (!s) return null;
  const cut = s.search(/[.:]\s+[A-Z(]/);
  const head = cut > 20 ? s.slice(0, cut + 1) : s;
  return head.length > max ? head.slice(0, max - 1).trimEnd() + '…' : head;
}

/**
 * WHAT RUNS, WHEN, AND WHETHER IT HAS ACTUALLY RUN.
 *
 * Added 2026-08-25 (Session 18, Item B tab 3). The schedule is read from the
 * SAME `config/daily-schedule.json` the Worker's own `runScheduledBlock()`
 * reads — passed in by the caller, never a second copy — so a block that is
 * shown here is a block that fires.
 *
 * ── WHAT THIS DELIBERATELY DOES NOT CLAIM ────────────────────────────────
 *
 * "When it last ran" is not a thing the office records per block. There is no
 * block-execution log, and inventing one out of nearby timestamps would produce
 * a page that looks like an instrument and is a guess. So each block is joined
 * to the artifact it PRODUCES where such an artifact exists and is in the
 * database — a meeting block to that meeting type's most recent row — and every
 * block where no such join exists says `no observable artifact` in those words.
 *
 * The counts are per TYPE and over all time, which is what the office's own
 * tables can answer cheaply. Two GROUP BY queries, not one per block: this
 * Worker has had scheduled work refused for crossing the 50-subrequest ceiling.
 */
export function buildAutomation({ schedule = null, meetingStats = [], reportStats = [] } = {}) {
  const dayTypes = [
    ['Sunday–Thursday', schedule?.full_day_schedule],
    ['Friday (short day)', schedule?.friday_schedule],
    ['Saturday (rest day)', schedule?.saturday_schedule],
  ];

  const meetingsByType = new Map();
  for (const row of meetingStats || []) {
    if (row && row.type) meetingsByType.set(String(row.type), row);
  }

  const blocks = [];
  for (const [dayLabel, sched] of dayTypes) {
    for (const b of (sched?.blocks || [])) {
      const evidence = b.meeting_type && meetingsByType.has(b.meeting_type)
        ? {
          joined_on: 'this meeting type in the office\'s database',
          last_at: meetingsByType.get(b.meeting_type).last_at || null,
          count: Number(meetingsByType.get(b.meeting_type).count) || 0,
        }
        : null;
      blocks.push({
        day_type: dayLabel,
        time: b.time || null,
        type: b.type || null,
        meeting_type: b.meeting_type || null,
        label: firstSentence(b.label),
        evidence,
        // Said in the payload rather than left to the page to infer, so the
        // absence is data and not a rendering accident.
        evidence_note: evidence
          ? null
          : 'no observable artifact — this block writes nothing the office can join back to it',
      });
    }
  }

  return {
    blocks,
    meeting_types: (meetingStats || []).map((m) => ({
      type: m.type || null, count: Number(m.count) || 0, last_at: m.last_at || null,
    })),
    report_types: (reportStats || []).map((r) => ({
      type: r.type || null, count: Number(r.count) || 0, last_at: r.last_at || null,
    })),
    notes: [
      'These are the blocks the office\'s scheduler actually iterates — read from the same configuration file the Worker reads, not a copy kept for this page.',
      'A block only fires if a Cloudflare cron tick lands on its exact minute. That tick window is declared in the Worker\'s deployment configuration and CANNOT BE READ FROM INSIDE THE WORKER, so this page cannot show it and does not pretend to.',
      'There is no per-block execution log anywhere in the office. Where a block produces something the database holds, it is joined to it; where it does not, this says so rather than inferring a run from a nearby timestamp.',
      'Counts are over all time, not today.',
    ],
  };
}

/**
 * Recent office activity from D1 — reports written and meetings held.
 *
 * **NO TRANSCRIPTS AND NO REPORT BODIES.** The caller selects titles and
 * timestamps; this maps them. `meetings.transcript` and `reports.content` are
 * the two columns this estate most needs never to leak, and the way they do
 * not leak is that nothing selects them.
 *
 * NOT INCLUDED, and named in `data_gaps` rather than silently absent: the git
 * commit feed. `data.js` built it by shelling out to `git log` in two private
 * repos, which is precisely what a Worker cannot do and precisely why that
 * file froze. Reproducing it would mean paginating two GitHub Contents APIs on
 * every page load. It is a real gap; it is not a pretended one.
 */
export function buildActivity({ reports = [], meetings = [] } = {}) {
  const out = [];
  for (const r of reports) {
    out.push({
      kind: 'report',
      repo: null,
      date: r.created_at || null,
      sort_key: r.created_at || '',
      agent_id: Number.isFinite(Number(r.agent_id)) ? Number(r.agent_id) : null,
      type: r.type || null,
      severity: r.severity || null,
      message: r.title || null,
    });
  }
  for (const m of meetings) {
    out.push({
      kind: 'meeting',
      repo: null,
      date: m.created_at || null,
      sort_key: m.created_at || '',
      agent_id: null,
      type: m.type || null,
      severity: null,
      message: `${m.type || 'meeting'} — ${m.attendee_count ?? '?'} attending`,
    });
  }
  return out.sort((a, b) => String(b.sort_key).localeCompare(String(a.sort_key)));
}

/**
 * THE ADMIN RESPONSE. Authenticated. Full data.
 *
 * `errors` is carried through rather than swallowed, and that is the same
 * judgement `buildOwnerState()` made for the same reason: a surface that
 * silently omitted the office's own read errors would be the most misleading
 * one in the system — the owner would read an empty pending list as "nothing
 * is waiting on me" when the truth was "the office could not read its board".
 */
export function buildAdminData({
  agents = [], counts = {}, snapshot = null,
  reports = [], meetings = [], generatedAt = null, versionId = null,
  // Session 18, Item B. All three injected, none imported — see the file
  // header's rule and `buildPendingItems()`'s note on why the three-part shape
  // is not written a second time in this module.
  noticeParts = null, schedule = null, meetingStats = [], reportStats = [],
} = {}) {
  const list = Array.isArray(agents) ? agents : [];
  const snapshotReadable = !!(snapshot && (snapshot.board || snapshot.requirements));

  return {
    ok: true,
    surface: 'admin',
    generated_at: typeof generatedAt === 'string' ? generatedAt : null,
    generated_by: `site-data.js (live, Worker version ${versionId || 'unknown'})`,
    agents: list.map((a) => ({
      id: Number(a.id),
      slug: agentSlug(a),
      name: a.name || null,
      title: `AGENT ${a.id} — ${String(a.name || '').toUpperCase()}`,
      role: a.role || null,
      purpose: a.purpose || null,
      character: a.character || null,
      tier: a.tier || null,
      clearance: a.clearance || null,
      status: a.status || null,
      live: a.status === 'active',
      has_persona: !!a.character,
      // Named, not omitted — see ADMIN_CONTRACT_KEYS' note.
      produced: [],
      bible_detail: null,
    })),
    counts: publicCounts(counts),
    pending_items: buildPendingItems(snapshot, { noticeParts }),
    activity: buildActivity({ reports, meetings }),
    automation: buildAutomation({ schedule, meetingStats, reportStats }),
    // The office's own errors reading its own files. Reported, never hidden.
    errors: Array.isArray(snapshot?.errors) ? snapshot.errors : [],
    data_gaps: [
      snapshotReadable
        ? 'pending_items is live: the board, the open questions and the submissions ledger, read from back-office at request time.'
        : 'THE OFFICE COULD NOT READ ITS OWN BOARD. pending_items is empty because the read failed, NOT because nothing is pending — see `errors`.',
      'bible_detail is null. The character bible is a private root document and the Worker does not fetch it; the built site carries its own copy, which does not go stale.',
      'produced is empty. It is a directory inventory of each agent\'s campus folder — a filesystem walk of a private repo, which a Worker has no filesystem to perform.',
      'activity carries reports and meetings from the office\'s database, with NO report bodies and NO meeting transcripts — those columns are never selected.',
      'activity does NOT carry the git commit feed. data.js built that by shelling out to `git log` in two private repos, which is exactly what a Worker cannot do and exactly why that file froze on 2026-08-07.',
      'Counts are totals since the simulation began on 2026-06-17, not per-day figures.',
      typeof noticeParts === 'function'
        ? 'Each pending item carries the ask, the options and the office\'s default composed by THE SAME function that writes its emails and Issues — one composition, not a second one written for this page.'
        : 'THE THREE-PART SHAPE IS MISSING from every pending item: the composer was not passed to this builder, so `notice` is null. The cards will show what the board says and not what the office would have asked you.',
      'An answer typed on this page stops the office repeating an item ONLY where `answer_stops_the_asking` is true — the channel\'s own reader matches the ledger ids, and a board task is not one of them. Each card says which it is.',
      'The automation list is what the scheduler iterates, joined to the office\'s database where a block leaves an artifact. There is no per-block execution log, and no block\'s run is inferred from a nearby timestamp.',
    ],
  };
}
